#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pypowerflex
Version  : 1.6.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/a2/65/0f35cc87811ffb48b785c17c0ff3f4de9c7fb8c733ff14b0f0e2492d2deb/PyPowerFlex-1.6.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a2/65/0f35cc87811ffb48b785c17c0ff3f4de9c7fb8c733ff14b0f0e2492d2deb/PyPowerFlex-1.6.0.tar.gz
Summary  : Python library for Dell PowerFlex
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-pypowerflex-license = %{version}-%{release}
Requires: pypi-pypowerflex-python = %{version}-%{release}
Requires: pypi-pypowerflex-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(packaging)
BuildRequires : pypi(requests)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# PyPowerFlex
Python SDK for Dell PowerFlex.
Supports PowerFlex (VxFlex OS) version 3.0 and later.

%package license
Summary: license components for the pypi-pypowerflex package.
Group: Default

%description license
license components for the pypi-pypowerflex package.


%package python
Summary: python components for the pypi-pypowerflex package.
Group: Default
Requires: pypi-pypowerflex-python3 = %{version}-%{release}

%description python
python components for the pypi-pypowerflex package.


%package python3
Summary: python3 components for the pypi-pypowerflex package.
Group: Default
Requires: python3-core
Provides: pypi(pypowerflex)
Requires: pypi(packaging)
Requires: pypi(requests)

%description python3
python3 components for the pypi-pypowerflex package.


%prep
%setup -q -n PyPowerFlex-1.6.0
cd %{_builddir}/PyPowerFlex-1.6.0
pushd ..
cp -a PyPowerFlex-1.6.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1675391747
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pypowerflex
cp %{_builddir}/PyPowerFlex-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pypowerflex/06a39f7f35acfc238a4051640bc043101312da57 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pypowerflex/06a39f7f35acfc238a4051640bc043101312da57

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
